//! `requirements.txt` parsing: `-r` includes, `-e` editables, `-c`
//! constraints, and -- the critical case -- pip-compile lockfile detection.
//!
//! A `requirements.txt` may secretly be a lockfile (edx-platform's
//! `base.txt` has 301 entries of which ~240 are transitive). Diffing
//! against it naively would report ~240 packages as "unused." When the
//! `# autogenerated by pip-compile`-style header is detected, we prefer a
//! sibling `.in` file if present, else recover the direct set from
//! per-entry `# via` annotations. See CLAUDE.md non-negotiable #5.

use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use super::{Dependency, DetectorResult, parse_requirement};

pub(crate) fn load(root: &Path) -> Option<DetectorResult> {
    let path = root.join("requirements.txt");
    if !path.is_file() {
        return None;
    }

    let mut warnings = Vec::new();
    let Ok(contents) = fs::read_to_string(&path) else {
        warnings.push(format!("Couldn't read '{}'.", path.display()));
        return Some(DetectorResult {
            path,
            dependencies: Vec::new(),
            warnings,
        });
    };

    if is_pip_compile_output(&contents) {
        return Some(load_pip_compile_output(&path, &contents));
    }

    let mut visited = HashSet::new();
    let dependencies = load_requirements_file(&path, &mut warnings, &mut visited);
    Some(DetectorResult {
        path,
        dependencies,
        warnings,
    })
}

fn is_pip_compile_output(contents: &str) -> bool {
    contents
        .lines()
        .take(15)
        .any(|line| line.to_lowercase().contains("pip-compile"))
}

fn load_pip_compile_output(path: &Path, contents: &str) -> DetectorResult {
    let mut warnings = Vec::new();

    let sibling_in = path.with_extension("in");
    if sibling_in.is_file() {
        warnings.push(format!(
            "'{}' is generated by pip-compile. scant read direct dependencies from \
             '{}' instead of diffing the compiled output.",
            path.display(),
            sibling_in.display()
        ));
        let mut visited = HashSet::new();
        let dependencies = load_requirements_file(&sibling_in, &mut warnings, &mut visited);
        return DetectorResult {
            path: sibling_in,
            dependencies,
            warnings,
        };
    }

    warnings.push(format!(
        "'{}' is generated by pip-compile. scant kept only the entries marked \
         directly requested ('# via -r ...' or no via annotation) and skipped \
         the rest as transitive.",
        path.display()
    ));

    let entries = parse_pip_compile_entries(contents);
    let mut dependencies = Vec::new();
    for entry in &entries {
        if !entry.is_direct() {
            continue;
        }
        let line = entry.raw.trim().trim_end_matches('\\').trim();
        match parse_requirement(line) {
            Ok(dep) => dependencies.push(dep),
            Err(_) => warnings.push(format!(
                "Couldn't parse a dependency line in '{}': '{line}' -- skipped it.",
                path.display()
            )),
        }
    }

    DetectorResult {
        path: path.to_path_buf(),
        dependencies,
        warnings,
    }
}

struct PipCompileEntry {
    raw: String,
    via: Vec<String>,
}

impl PipCompileEntry {
    /// `# via -r foo.in` (or no `# via` annotation at all) = direct;
    /// `# via somepackage` = transitive.
    fn is_direct(&self) -> bool {
        self.via.is_empty() || self.via.iter().any(|v| v.trim_start().starts_with("-r "))
    }
}

/// Parses pip-compile's output shape: a top-level requirement line followed
/// by indented comment continuation lines recording where it came from,
/// e.g.:
/// ```text
/// attrs==23.1.0
///     # via
///     #   jsonschema
///     #   referencing
/// requests==2.31.0
///     # via -r requirements.in
/// ```
fn parse_pip_compile_entries(contents: &str) -> Vec<PipCompileEntry> {
    let mut entries = Vec::new();
    let mut current: Option<PipCompileEntry> = None;

    for line in contents.lines() {
        let is_continuation = line.starts_with(' ') || line.starts_with('\t');
        let trimmed = line.trim_start();

        if is_continuation {
            if let Some(entry) = current.as_mut()
                && let Some(comment) = trimmed.strip_prefix('#')
            {
                let comment = comment.trim();
                if let Some(rest) = comment.strip_prefix("via") {
                    let rest = rest.trim();
                    if !rest.is_empty() {
                        entry.via.push(rest.to_string());
                    }
                } else if !comment.is_empty() {
                    entry.via.push(comment.to_string());
                }
            }
            continue;
        }

        if trimmed.is_empty() || trimmed.starts_with('#') {
            if let Some(entry) = current.take() {
                entries.push(entry);
            }
            continue;
        }

        if let Some(entry) = current.take() {
            entries.push(entry);
        }
        current = Some(PipCompileEntry {
            raw: line.to_string(),
            via: Vec::new(),
        });
    }
    if let Some(entry) = current.take() {
        entries.push(entry);
    }

    entries
}

/// Loads a plain, hand-written requirements-style file (used both for a
/// real `requirements.txt` and for any file it `-r`-includes, recursively).
fn load_requirements_file(
    path: &Path,
    warnings: &mut Vec<String>,
    visited: &mut HashSet<PathBuf>,
) -> Vec<Dependency> {
    let mut dependencies = Vec::new();

    let canonical = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
    if !visited.insert(canonical) {
        warnings.push(format!(
            "'{}' includes itself, directly or via a cycle -- skipped the repeat.",
            path.display()
        ));
        return dependencies;
    }

    let Ok(contents) = fs::read_to_string(path) else {
        warnings.push(format!("Couldn't read '{}' -- skipped it.", path.display()));
        return dependencies;
    };

    for raw_line in contents.lines() {
        let trimmed = raw_line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if let Some(rest) = strip_flag(trimmed, &["-e", "--editable"]) {
            match parse_editable(rest.trim()) {
                Some(dep) => dependencies.push(dep),
                None => warnings.push(format!(
                    "Couldn't figure out a package name for the editable install \
                     '{rest}' in '{}' -- skipped it.",
                    path.display()
                )),
            }
            continue;
        }

        if let Some(rest) = strip_flag(trimmed, &["-r", "--requirement"]) {
            let included = resolve_included_path(path, rest.trim());
            dependencies.extend(load_requirements_file(&included, warnings, visited));
            continue;
        }

        if strip_flag(trimmed, &["-c", "--constraint"]).is_some() {
            // Constraints, not declarations -- never a direct dependency.
            continue;
        }

        if trimmed.starts_with('-') {
            // Some other pip option (--hash, --index-url, etc.) -- not a dependency.
            continue;
        }

        let without_comment = strip_inline_comment(trimmed).trim();
        if without_comment.is_empty() {
            continue;
        }

        match parse_requirement(without_comment) {
            Ok(dep) => dependencies.push(dep),
            Err(_) => warnings.push(format!(
                "Couldn't parse a dependency line in '{}': '{without_comment}' -- skipped it.",
                path.display()
            )),
        }
    }

    dependencies
}

fn strip_flag<'a>(line: &'a str, flags: &[&str]) -> Option<&'a str> {
    for flag in flags {
        if let Some(rest) = line.strip_prefix(flag) {
            if let Some(stripped) = rest.strip_prefix(' ') {
                return Some(stripped);
            }
            if let Some(stripped) = rest.strip_prefix('=') {
                return Some(stripped);
            }
        }
    }
    None
}

/// Strips a trailing inline comment (` # ...`). Deliberately requires a
/// preceding space before `#` so it doesn't mangle a `-e` editable spec's
/// `#egg=name` URL fragment (those are handled before this ever runs).
fn strip_inline_comment(line: &str) -> &str {
    match line.find(" #") {
        Some(idx) => &line[..idx],
        None => line,
    }
}

fn resolve_included_path(current_file: &Path, included: &str) -> PathBuf {
    let token = included.split_whitespace().next().unwrap_or(included);
    let candidate = PathBuf::from(token);
    if candidate.is_absolute() {
        candidate
    } else {
        current_file
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join(candidate)
    }
}

/// Best-effort name extraction for `-e`/`--editable` lines, per
/// plans/Phase1.md's judgment call: prefer `#egg=name`, else a plain PEP 508
/// parse, else the path/dir basename. Returns `None` (never crashes) if
/// nothing usable can be extracted.
fn parse_editable(spec: &str) -> Option<Dependency> {
    if let Some(idx) = spec.find("#egg=") {
        let after = &spec[idx + "#egg=".len()..];
        let name_part: String = after.chars().take_while(|c| *c != '&').collect();
        if !name_part.is_empty()
            && let Ok(name) = pep508_rs::PackageName::new(name_part.clone())
        {
            return Some(Dependency {
                name,
                display_name: name_part,
            });
        }
    }

    if let Ok(dep) = parse_requirement(spec) {
        return Some(dep);
    }

    let path_part = spec
        .split(['@', '#'])
        .next()
        .unwrap_or(spec)
        .trim()
        .trim_end_matches('/');
    let basename = path_part.rsplit(['/', '\\']).next().unwrap_or(path_part);
    let candidate = basename.trim_end_matches(".git");
    if candidate.is_empty() {
        return None;
    }
    pep508_rs::PackageName::new(candidate.to_string())
        .ok()
        .map(|name| Dependency {
            name,
            display_name: candidate.to_string(),
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn temp_dir(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("scant-requirements-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn missing_file_returns_none() {
        let dir = temp_dir("missing");
        assert!(load(&dir).is_none());
        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn plain_lines_blank_and_comment_skipping() {
        let dir = temp_dir("plain");
        fs::write(
            dir.join("requirements.txt"),
            "requests==2.31.0\n\n# a comment\nclick>=8.0\n",
        )
        .unwrap();

        let result = load(&dir).unwrap();
        let names: Vec<_> = result
            .dependencies
            .iter()
            .map(|d| d.display_name.clone())
            .collect();
        assert_eq!(names, vec!["requests", "click"]);

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn dash_r_include_is_followed() {
        let dir = temp_dir("include");
        fs::write(dir.join("requirements.txt"), "-r base.txt\nclick\n").unwrap();
        fs::write(dir.join("base.txt"), "requests\n").unwrap();

        let result = load(&dir).unwrap();
        let names: HashSet<_> = result
            .dependencies
            .iter()
            .map(|d| d.display_name.clone())
            .collect();
        assert_eq!(
            names,
            HashSet::from(["requests".to_string(), "click".to_string()])
        );

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn cyclic_include_is_guarded() {
        let dir = temp_dir("cycle");
        fs::write(dir.join("requirements.txt"), "-r other.txt\nclick\n").unwrap();
        fs::write(dir.join("other.txt"), "-r requirements.txt\nrequests\n").unwrap();

        let result = load(&dir).unwrap();
        let names: HashSet<_> = result
            .dependencies
            .iter()
            .map(|d| d.display_name.clone())
            .collect();
        assert_eq!(
            names,
            HashSet::from(["requests".to_string(), "click".to_string()])
        );
        assert!(result.warnings.iter().any(|w| w.contains("cycle")));

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn dash_c_constraint_is_skipped_not_declared() {
        let dir = temp_dir("constraint");
        fs::write(
            dir.join("requirements.txt"),
            "-c constraints.txt\nrequests\n",
        )
        .unwrap();
        fs::write(dir.join("constraints.txt"), "urllib3==2.0.0\n").unwrap();

        let result = load(&dir).unwrap();
        let names: Vec<_> = result
            .dependencies
            .iter()
            .map(|d| d.display_name.clone())
            .collect();
        assert_eq!(names, vec!["requests"]);

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn editable_path_form_uses_egg_fragment() {
        let dir = temp_dir("editable-egg");
        fs::write(dir.join("requirements.txt"), "-e ./local/mypkg#egg=mypkg\n").unwrap();

        let result = load(&dir).unwrap();
        assert_eq!(result.dependencies.len(), 1);
        assert_eq!(result.dependencies[0].display_name, "mypkg");

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn editable_git_url_with_egg_fragment() {
        let dir = temp_dir("editable-git");
        fs::write(
            dir.join("requirements.txt"),
            "-e git+https://github.com/example/foo.git@main#egg=foo\n",
        )
        .unwrap();

        let result = load(&dir).unwrap();
        assert_eq!(result.dependencies.len(), 1);
        assert_eq!(result.dependencies[0].display_name, "foo");

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn editable_without_egg_falls_back_to_path_basename() {
        let dir = temp_dir("editable-basename");
        fs::write(dir.join("requirements.txt"), "-e ./local/mypkg\n").unwrap();

        let result = load(&dir).unwrap();
        assert_eq!(result.dependencies.len(), 1);
        assert_eq!(result.dependencies[0].display_name, "mypkg");

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn pip_compile_header_prefers_sibling_in_file() {
        let dir = temp_dir("pip-compile-sibling");
        fs::write(
            dir.join("requirements.txt"),
            "#\n# This file is autogenerated by pip-compile\n#\nattrs==23.1.0\n    # via -r requirements.in\njsonschema==4.0.0\n    # via attrs\n",
        )
        .unwrap();
        fs::write(dir.join("requirements.in"), "attrs\n").unwrap();

        let result = load(&dir).unwrap();
        assert_eq!(result.dependencies.len(), 1);
        assert_eq!(result.dependencies[0].display_name, "attrs");
        assert!(result.path.ends_with("requirements.in"));

        fs::remove_dir_all(&dir).unwrap();
    }

    /// The edx-platform trap: a compiled lockfile with no sibling `.in`
    /// must resolve only the directly-requested entries via `# via`
    /// provenance, never the transitive ones. This is the single most
    /// important test in this module.
    #[test]
    fn pip_compile_via_annotations_separate_direct_from_transitive() {
        let dir = temp_dir("pip-compile-via");
        let contents = "\
#
# This file is autogenerated by pip-compile with Python 3.11
# To update, run:
#
#    pip-compile requirements.in
#
attrs==23.1.0
    # via
    #   jsonschema
    #   referencing
certifi==2023.7.22
    # via requests
jsonschema==4.19.0
    # via -r requirements.in
referencing==0.30.0
    # via jsonschema
requests==2.31.0
    # via -r requirements.in
";
        fs::write(dir.join("requirements.txt"), contents).unwrap();

        let result = load(&dir).unwrap();
        let names: HashSet<_> = result
            .dependencies
            .iter()
            .map(|d| d.display_name.clone())
            .collect();
        // Only the two entries marked "via -r requirements.in" are direct;
        // attrs/certifi/referencing are pulled in transitively and must be
        // excluded, never flagged as "unused" the way a naive diff would.
        assert_eq!(
            names,
            HashSet::from(["jsonschema".to_string(), "requests".to_string()])
        );

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn pip_compile_entry_with_no_via_annotation_counts_as_direct() {
        let dir = temp_dir("pip-compile-no-via");
        let contents = "# This file is autogenerated by pip-compile\nstandalone-pkg==1.0.0\n";
        fs::write(dir.join("requirements.txt"), contents).unwrap();

        let result = load(&dir).unwrap();
        assert_eq!(result.dependencies.len(), 1);
        assert_eq!(result.dependencies[0].display_name, "standalone-pkg");

        fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn non_pip_compile_file_treats_every_entry_as_direct() {
        let dir = temp_dir("hand-written");
        fs::write(dir.join("requirements.txt"), "requests\nclick\n").unwrap();

        let result = load(&dir).unwrap();
        assert_eq!(result.dependencies.len(), 2);

        fs::remove_dir_all(&dir).unwrap();
    }
}
